FROM python:3.9-slim as build-stage
WORKDIR /app
COPY requirement.txt ./
RUN pip3 install --no-cache-dir -r requirement.txt
COPY . .


FROM python:3.9-slim
WORKDIR /app
COPY --from=build-stage /app /app
EXPOSE 5000
ENTRYPOINT [ "python3" ]
CMD ["main.py"]



#docker build -t my-flask-app .

#docker run -d -p 5000:5000 my-flask-app 

