FROM python:3.9-slim as build-stage
WORKDIR /app
COPY requirement.txt ./
RUN pip3 install --no-cache-dir -r requirement.txt
COPY . .


FROM python:3.9-slim
WORKDIR /app
COPY --from=build-stage /app /app
EXPOSE 5000
CMD ["python3", "main.py"]

