- name: my-playbook
  hosts: all
  var:
    input1: name
    lst: [ 1,2,3,4,5,4 ]
    dict: 
      bob:
        puni: engineer
        jani: CA 
  tasks:
    - name: print Puni occupation
      debug:
        msg: Punit is an {{ dict.bob.puni }}   

    - name: print jani occupation
      debug:
        msg: Janit is a {{ dict.bob.jani }}  


# we can also create vars.yaml file and put all the variable in that file. and import it 
# using vars_files=vars.yaml 

#You can use the vars_prompt keyword to prompt the user to set a variable’s value
#at runtime.